version: 0.1

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo ${test}
      - echo Building the application
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'