version: 0.2

environment_variables:
  plaintext:
    SECRET_KEY: ${SECRET_KEY}
    PSQL_NAME: ${PSQL_NAME}
    PSQL_USER: ${PSQL_USER}
    PSQL_PASSWORD: ${PSQL_PASSWORD}
    PSQL_HOST: ${PSQL_HOST}
    PSQL_PORT: ${PSQL_PORT}
    TMDB_API_KEY: ${TMDB_API_KEY}
    RS_URL: ${RS_URL}

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
      - aws ssm get-parameters --names SECRET_KEY --with-decryption --query Parameters[*].Value --output text > env.sh
      - chmod +x env.sh
      - ./env.sh
      - echo pre_build test env var ${SECRET_KEY}
  build:
    commands:
      - echo test env var ${test}
      - echo Building the application
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'